### ISSUE TITLE
How could I run your example?

### ISSUE THREAD

**Issue by LimHyungTae** [Whojo/PyBind_example#1]
Hello, hope you have great these days.

Recently, I wanna study pybinding and I saw your code. But when I build and run the .py, the error occurs as follows:

```
> python3 hello.py
Traceback (most recent call last):
  File "hello.py", line 3, in <module>
    from hello import Test
  File "/home/shapelim/lib/PyBind_example/hello.py", line 3, in <module>
    from hello import Test
ImportError: cannot import name 'Test' from partially initialized module 'hello' (most likely due to a circular import) (/home/shapelim/lib/PyBind_example/hello.py)
```

Could you provide me with a more detailed explanation of how I could run your codes? Thank you in advance.

**Comment by LimHyungTae** [comment]
Oh, I found how to run, haha. Thanks!
